# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: false
cache: packages
language: r
r:
  - oldrel
  - release
  - devel

pandoc_version: 2.5

after_success:
  - Rscript -e 'covr::codecov()'

r_check_args: "--as-cran --run-dontrun"

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    branch: master
    condition: "$TRAVIS_R_VERSION_STRING = release"
