    
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel
cache:
  packages: false

sudo: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'